# -*- coding: utf-8 -*-
"""test_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3FD9jRUJ_bmubCe8CDFoRbxyrv3Y_Z1
"""

import requests, sys

URL = "https://sthomas10-nba-predictor.hf.space/predict"

resp = requests.post(URL, json={"home_team": "LAL", "away_team": "BOS"})
assert resp.status_code == 200, f"Bad status: {resp.status_code}"

data = resp.json()
assert "home_win_prob" in data, "Missing home_win_prob"
assert "away_win_prob" in data, "Missing away_win_prob"
assert 0 <= data["home_win_prob"] <= 100, "Probability out of range"

print("✅ All tests passed.")
sys.exit(0)